### ISSUE TITLE
Database page test coverage

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolthub-cypress#267]
When we redeveloped the database page a few months ago, we didn't bring the database page tests up to speed. We have some basic tests, but we need tests for: 
- Left repo nav tabs
  - [x] Written
  - [x] Deployed
- Add item dropdown (logged in vs logged out)
  - [x] Written
  - [x] Deployed
- Left repo, in depth nav tabs
  - [x] Written
  - [x] Deployed

**Comment by cheshirekate8** [comment]
Done!
